### ISSUE TITLE
Unable to transcribe YouTube videos in Chinese

### ISSUE THREAD

**Issue by ChillSoulGames** [zackees/transcribe-anything#15]
transcribe-anything --language Chinese --device insane https://www.youtube.com/watch?v=m7huzFiIiGo

Python 3.11.7

{
    "cuda_available": true,
    "cuda_devices": [
        {
            "device_id": 0,
            "multiprocessors": 76,
            "name": "NVIDIA GeForce RTX 4080",
            "vram": 17170956288
        }
    ],
    "num_cuda_devices": 1
}
Running transcribe_audio on https://www.youtube.com/watch?v=m7huzFiIiGo
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 37: character maps to <undefined>
Error: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "C:\Users\x\desktop\t\venv\Lib\site-packages\transcribe_anything\cmd.py", line 188, in main
    transcribe(
  File "C:\Users\x\desktop\t\venv\Lib\site-packages\transcribe_anything\api.py", line 160, in transcribe
    output_dir = "text_" + yt_dlp.stdout.strip()
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

while processing https://www.youtube.com/watch?v=m7huzFiIiGo

**Comment by zackees** [comment]
Fixed in `2.7.28`.

Use `pip install -U transcribe-anything` to get the fix.
