### ISSUE TITLE
install torchaudio==2.1.2' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by mm86133** [zackees/transcribe-anything#18]
'C:\Python312\Lib\site-packages\transcribe_anything\venv\insanely_fast_whisper\Scripts\pip install torchaudio==2.1.2' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\transcribe_anything\_cmd.py", line 208, in main
    transcribe(
  File "C:\Python312\Lib\site-packages\transcribe_anything\api.py", line 251, in transcribe
    run_insanely_fast_whisper(
  File "C:\Python312\Lib\site-packages\transcribe_anything\insanely_fast_whisper.py", line 198, in run_insanely_fast_whisper
    env = get_environment()
          ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\transcribe_anything\insanley_fast_whisper_reqs.py", line 49, in get_environment
    env = isolated_environment(venv_dir, deps)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\isolated_environment\__init__.py", line 22, in isolated_environment
    iso_env = IsolatedEnvironment(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\isolated_environment\api.py", line 145, in __init__
    self.ensure_installed(requirements or Requirements([]))
  File "C:\Python312\Lib\site-packages\isolated_environment\api.py", line 324, in ensure_installed
    self.pip_install(
  File "C:\Python312\Lib\site-packages\isolated_environment\api.py", line 208, in pip_install
    _pip_install(self.env_path, package, build_options, full_isolation)
  File "C:\Python312\Lib\site-packages\isolated_environment\api.py", line 119, in _pip_install
    subprocess.run(cmd, env=act_env.env, shell=True, check=True)
  File "C:\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'C:\Python312\Lib\site-packages\transcribe_anything\venv\insanely_fast_whisper\Scripts\pip install torchaudio==2.1.2' returned non-zero exit status 1.

**Comment by przanowo** [comment]
same here.

**Comment by przanowo** [comment]
Solved with installing a virtual environment.

python -m venv transcribe_env
transcribe_env\Scripts\activate
pip install transcribe-anything

**Comment by zackees** [comment]
Last I checked - python 3.12 wasn't supported by the ML dependencies

**Comment by zackees** [comment]
Fixed with the newest release. I now use UV and a pinned python dependency.
