### ISSUE TITLE
'whisper' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by NakedRaccoon** [zackees/transcribe-anything#21]
Installed the package according to readme.md and tried to run command, but the following error occurred:
```
PS D:\python\transcriber> transcribe-anything https://www.youtube.com/watch?v=dQw4w9WgXcQ
'whisper' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Program Files (x86)\python\3115\Scripts\transcribe-anything.exe\__main__.py", line 7, in <module>
  File "D:\Program Files (x86)\python\3115\Lib\site-packages\transcribe_anything\_cmd.py", line 154, in main
    args = parse_arguments()
           ^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\python\3115\Lib\site-packages\transcribe_anything\_cmd.py", line 60, in parse_arguments
    whisper_options = get_whisper_options()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\python\3115\Lib\site-packages\transcribe_anything\_cmd.py", line 52, in get_whisper_options
    whisper_options = parse_whisper_options()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\python\3115\Lib\site-packages\transcribe_anything\parse_whisper_options.py", line 28, in parse_whisper_options
    stdout = subprocess.check_output(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\python\3115\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files (x86)\python\3115\Lib\subprocess.py", line 571, in run 
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'whisper --help' returned non-zero exit status 1.
```

**Comment by wonka929** [comment]
Same here.
Event pip install whisper does not solve the situation.

**Comment by biliboss** [comment]
Same here

**Comment by zackees** [comment]
I see that people are using powershell, does this also fail when launching from cmd.exe?

**Comment by NakedRaccoon** [comment]
> I see that people are using powershell, does this also fail when launching from cmd.exe?

Yes, I tried to run the command in admin cmd and the same prompt appeared as well.

**Comment by rapus95** [comment]
In cmd I ran into the same problem:
```
C:\Users\Aaron\Downloads\>sudo py -3.10 -m pip install transcribe-anything
WARNING: Ignoring invalid distribution -overage (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -overage (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Collecting transcribe-anything
  Using cached transcribe_anything-2.7.38-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: isolated-environment~=2.0.0 in c:\python310\lib\site-packages (from transcribe-anything) (2.0.0)
Requirement already satisfied: FileLock in c:\python310\lib\site-packages (from transcribe-anything) (3.15.4)
Requirement already satisfied: yt-dlp>=2023.3.4 in c:\python310\lib\site-packages (from transcribe-anything) (2024.8.6)
Requirement already satisfied: webvtt-py==0.4.6 in c:\python310\lib\site-packages (from transcribe-anything) (0.4.6)
Requirement already satisfied: disklru>=1.0.7 in c:\python310\lib\site-packages (from transcribe-anything) (1.0.7)
Requirement already satisfied: appdirs==1.4.4 in c:\python310\lib\site-packages (from transcribe-anything) (1.4.4)
Requirement already satisfied: static-ffmpeg>=2.7 in c:\python310\lib\site-packages (from transcribe-anything) (2.7)
Requirement already satisfied: docopt in c:\python310\lib\site-packages (from webvtt-py==0.4.6->transcribe-anything) (0.6.2)
Requirement already satisfied: setuptools in c:\python310\lib\site-packages (from isolated-environment~=2.0.0->transcribe-anything) (65.5.0)
Requirement already satisfied: semver in c:\python310\lib\site-packages (from isolated-environment~=2.0.0->transcribe-anything) (3.0.2)
Requirement already satisfied: wheel in c:\python310\lib\site-packages (from isolated-environment~=2.0.0->transcribe-anything) (0.44.0)
Requirement already satisfied: requests in c:\python310\lib\site-packages (from static-ffmpeg>=2.7->transcribe-anything) (2.32.3)
Requirement already satisfied: brotli in c:\python310\lib\site-packages (from yt-dlp>=2023.3.4->transcribe-anything) (1.1.0)
Requirement already satisfied: websockets>=12.0 in c:\python310\lib\site-packages (from yt-dlp>=2023.3.4->transcribe-anything) (12.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in c:\python310\lib\site-packages (from yt-dlp>=2023.3.4->transcribe-anything) (2.2.2)
Requirement already satisfied: certifi in c:\python310\lib\site-packages (from yt-dlp>=2023.3.4->transcribe-anything) (2024.7.4)
Requirement already satisfied: pycryptodomex in c:\python310\lib\site-packages (from yt-dlp>=2023.3.4->transcribe-anything) (3.20.0)
Requirement already satisfied: mutagen in c:\python310\lib\site-packages (from yt-dlp>=2023.3.4->transcribe-anything) (1.47.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests->static-ffmpeg>=2.7->transcribe-anything) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests->static-ffmpeg>=2.7->transcribe-anything) (3.3.2)
WARNING: Ignoring invalid distribution -overage (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Installing collected packages: transcribe-anything
WARNING: Ignoring invalid distribution -overage (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Successfully installed transcribe-anything-2.7.38
WARNING: Ignoring invalid distribution -overage (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -overage (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: There was an error checking the latest version of pip.

C:\Users\Aaron\Downloads>sudo transcribe-anything --help
Der Befehl "whisper" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\transcribe-anything.EXE\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\transcribe_anything\_cmd.py", line 154, in main
    args = parse_arguments()
  File "C:\Python310\lib\site-packages\transcribe_anything\_cmd.py", line 60, in parse_arguments
    whisper_options = get_whisper_options()
  File "C:\Python310\lib\site-packages\transcribe_anything\_cmd.py", line 46, in get_whisper_options
    whisper_options = parse_whisper_options()
  File "C:\Python310\lib\site-packages\transcribe_anything\parse_whisper_options.py", line 28, in parse_whisper_options
    stdout = subprocess.check_output(
  File "C:\Python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'whisper --help' returned non-zero exit status 1.
```

**Comment by rapus95** [comment]
managed to install openai-whisper. Still doesn't recognize it :/
```
C:\Users\Aaron\Downloads>sudo transcribe-anything --help
Der Befehl "whisper" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\transcribe-anything.EXE\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\transcribe_anything\_cmd.py", line 154, in main
    args = parse_arguments()
  File "C:\Python310\lib\site-packages\transcribe_anything\_cmd.py", line 60, in parse_arguments
    whisper_options = get_whisper_options()
  File "C:\Python310\lib\site-packages\transcribe_anything\_cmd.py", line 46, in get_whisper_options
    whisper_options = parse_whisper_options()
  File "C:\Python310\lib\site-packages\transcribe_anything\parse_whisper_options.py", line 28, in parse_whisper_options
    stdout = subprocess.check_output(
  File "C:\Python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'whisper --help' returned non-zero exit status 1.

C:\Users\Aaron\Downloads>whisper
usage: whisper [-h] [--model MODEL] [--model_dir MODEL_DIR] [--device DEVICE] [--output_dir OUTPUT_DIR]
               [--output_format {txt,vtt,srt,tsv,json,all}] [--verbose VERBOSE] [--task {transcribe,translate}]
               [--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,yue,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Cantonese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Mandarin,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}]
               [--temperature TEMPERATURE] [--best_of BEST_OF] [--beam_size BEAM_SIZE] [--patience PATIENCE]
               [--length_penalty LENGTH_PENALTY] [--suppress_tokens SUPPRESS_TOKENS] [--initial_prompt INITIAL_PROMPT]
               [--condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT] [--fp16 FP16]
               [--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
               [--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD] [--logprob_threshold LOGPROB_THRESHOLD]
               [--no_speech_threshold NO_SPEECH_THRESHOLD] [--word_timestamps WORD_TIMESTAMPS]
               [--prepend_punctuations PREPEND_PUNCTUATIONS] [--append_punctuations APPEND_PUNCTUATIONS]
               [--highlight_words HIGHLIGHT_WORDS] [--max_line_width MAX_LINE_WIDTH] [--max_line_count MAX_LINE_COUNT]
               [--max_words_per_line MAX_WORDS_PER_LINE] [--threads THREADS]
               audio [audio ...]
whisper: error: the following arguments are required: audio
```

**Comment by zackees** [comment]
Fixed in the most recent release.
