### ISSUE TITLE
Insane doesn't work properly in Python 3.12.4 on macOS Sequoia

### ISSUE THREAD

**Issue by elander** [zackees/transcribe-anything#29]
I'm getting this error:

`Error: Command '/opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/venv/insanely_fast_whisper/bin/pip install -r /opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/venv/insanely_fast_whisper/requirements.txt' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/_cmd.py", line 208, in main
    transcribe(
  File "/opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/api.py", line 250, in transcribe
    run_insanely_fast_whisper(
  File "/opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/insanely_fast_whisper.py", line 201, in run_insanely_fast_whisper
    env = get_environment()
          ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/insanley_fast_whisper_reqs.py", line 50, in get_environment
    env = isolated_environment(VENV_DIR, deps, full_isolation=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/isolated_environment/__init__.py", line 21, in isolated_environment
    iso_env = IsolatedEnvironment(
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/isolated_environment/api.py", line 136, in __init__
    self.ensure_installed(requirements)
  File "/opt/anaconda3/lib/python3.12/site-packages/isolated_environment/api.py", line 281, in ensure_installed
    _pip_install_all(self.env_path, reqs, self.full_isolation, args)
  File "/opt/anaconda3/lib/python3.12/site-packages/isolated_environment/api.py", line 110, in _pip_install_all
    subprocess.run(cmd, env=act_env.env, shell=True, check=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/venv/insanely_fast_whisper/bin/pip install -r /opt/anaconda3/lib/python3.12/site-packages/transcribe_anything/venv/insanely_fast_whisper/requirements.txt' returned non-zero exit status 1.

while processing https://youtu.be/xxxxxxx
`
The computer is a Mac mini, Apple M2 Pro, 32 GB RAM and 1 TB SSD.

The video is unlisted and should not be made available for the general public, which is why I obfuscated the URL. It transcribes properly without -- device insane, so that's not an issue.

**Comment by zackees** [comment]
Fixed with the most recent release.
